### PR TITLE
Fix logic error in splitBy function

### LINKED ISSUE #108: Fix area plotting
I think I broke areas at some point during the refactor. Looking at the sandbox, the first point in each area is missing.

We probably need to cherry-pick the sandbox onto an old version, rebase everything else on top of that, then bisect.

### PR DESCRIPTION
**Pull request by nabeel-**
Closes #108

### CODE REVIEW

File: src/plot/areas.js [hunk 1]
```diff
@@ -13,18 +25,12 @@ export function isPlotNumber(value) {
...
-function splitBy(arr, iteratee) {
-  const {sliceFrom, returnArray} = arr.reduce(
+export function splitBy(arr, iteratee) {
+  return arr.reduce(
     (acc, val, idx) =>
-      iteratee(val, idx)
-        ? {sliceFrom: idx, returnArray: [...acc.returnArray, slice(arr, acc.sliceFrom, idx)]}
-        : acc,
-    {sliceFrom: 0, returnArray: []}
+      iteratee(val, idx) ? [...acc, []] : [...initial(acc), last(acc).concat([val])],
```
Comment (jhhayashi) [inline src/plot/areas.js]: could keep consistency by using array spread rather than `.concat()`:
`[...initial(acc), [...last(acc), val]]`

Comment (nabeel-) [reply src/plot/areas.js]: Seems like a good idea! Updated

**Comment by billyjanitsch** [comment]
Thanks! The logic looks correct to me but this is a _lot_ of large array allocations to be doing N times. I think we should circle back and optimize this function.
